  
baseURL = "https://yjhmelody.github.io"
languageCode = "cn-zh"
title = "Minimal"
theme = "minimal"
disqusShortname = "yjhmelody" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "yjhmelody"
    description = "Personal blog"
    githubUsername = "yjhmelody"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    # font = "Raleway" # should match the name on Google Fonts!
    font = "Fira Code Retina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["rust", "cpp", "go", "haskell", "kotlin", "scala", "swift"]
    
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Posts"
    weight = 3

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:465402634@qq.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/yjhmelody/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/yjhmelody/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.douban.com/people/yjhmelody/"
    name = "douban"
    weight = 4

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5


# publishDir = "docs"